version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test

      - image: circleci/redis:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: npm-install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: amorphic-daemon-pipeline
        command: cd angular-daemon


      # unit tests
      - run:
          name: test
          command: npm run test

      # linting
      - run:
          name: lint
          command: npm run lint