version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
      - image: circleci/redis:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
    working_directory: angular-daemon
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: npm-install
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules

      # unit tests
      - run:
          name: daemon test
          command: npm run test

      # linting
      - run:
          name: daemon lint
          command: npm run lint